@startuml classdiagram

class Circuit {
    - mMapVertexes : map<string,Vertex>
    - mMapConnections : map<string,string>
}

class FileToGraph {
    - mInputFile : FILE
}

class CircuitSim {
    + runSim() : void
}

class ResultToFile {
    - mOutputFile : FILE
}

class OrGate{

}

class AndGate{

}

class NorGate{

}

class NandGate{

}

class XorGate{

}

class NotGate{

}

class Gate{
    - *mInput : int
    - mOutput : int
    - mAmountInputs : int

    - mMinInputs : int
    - mMaxInputs : int    

    + setInput(int aIndex, bool aValue) override : void
    + getOutput() : int
    + setAmountInputs(int aInputs) : void
}

class Vertex {
    - mEdge : Edge*

    + setInput(int aIndex, bool aValue) virtual : void
}

class Edge {
    - mNext : Vertex**
    - mVertexInputIndex : int
    - mAmountVertex : int

    + setIntput(bool aValue) : void
}

class Input {
    - mValue : int

    + mSetValue(bool) : void
    + setInput(int aIndex, bool aValue) override : void

}

class Probe {
    - mValue : int

    + getValue() : bool
    + setInput(int aIndex, bool aValue) override : void
}

FileToGraph *-- Circuit
ResultToFile *-- Circuit

Circuit <-- Vertex

CircuitSim <-- Circuit

OrGate --|> Gate
NorGate --|> Gate
AndGate --|> Gate
NandGate --|> Gate
XorGate --|> Gate
NotGate --|> Gate

Gate --|> Vertex
Input --|> Vertex
Probe --|> Vertex

Vertex --* "0..1" Edge
Edge --o "1..*" Vertex

@enduml